version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: ./Dashboard/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      
  node:
    build:
      context: .
      dockerfile: ./Node/Dockerfile
    ports:
      - "8080:8080"