apiVersion: v1
kind: Service
metadata:
  name: colour
  namespace: default
spec:
  type: NodePort
  selector:
    app: colour
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32082
