apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/KevReece/KubernetesRollout/'
    targetRevision: HEAD
    path: 'k8s-manifests/base'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
