apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: node
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10s}
      - setWeight: 40
      - pause: {duration: 10s}
      - setWeight: 60
      - pause: {duration: 10s}
      - setWeight: 80
      - pause: {duration: 10s}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: dashboard
        image: kubernetesrollout_node:blue
        imagePullPolicy: Never
